spring:
  application:
    name: spring-cloud-eureka-client
server:
  port: 8090
  servlet:
    context-path: /api
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
    hostname: localhost
    lease-renewal-interval-in-seconds: 15